name: Streamlit App Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up .env variables
      - name: Add .env Variables
        env:
          STABILITY_API: ${{ secrets.STABILITY_API }}
        run: |
          echo "STABILITY_API=${{ secrets.STABILITY_API }}" >> .env

          - name: Check STABILITY_API
          if [ -z "$STABILITY_API" ]; then echo "STABILITY_API is not set"; else echo "STABILITY_API is set"; fi


      # Step 5: Run the Streamlit app
      - name: Run Streamlit App
        run: |
          streamlit run streamlit_app.py
