name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a requirements.txt file

    - name: Run Streamlit App
      env:
        STABILITY_KEY: ${{ secrets.STABILITY_API}}
      run: |
        streamlit run app.py  # Replace with your app filename
